# Generated by Django 3.2.7 on 2021-11-23 15:14

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20211123_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='blog',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/media/blogimages'), upload_to=''),
        ),
    ]
