# Generated by Django 3.2.7 on 2021-11-23 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_image_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='image',
        ),
    ]
